### ISSUE TITLE
display error

### ISSUE THREAD

**Issue by ghost** [clarkwinkelmann/catch-the-fish#13]
extension not showing in admin panel

**Comment by clarkwinkelmann** [comment]
Hi, sorry for the long response delay.

These kind of issue is probably not an issue with my extension, but probably a cache issue on your server or in your browser. Try Flarum's [Troubleshooting steps](https://docs.flarum.org/troubleshoot/) to see if anything changes.

If you need further help, please create a support discussion on the [Flarum community](https://discuss.flarum.org/) or Flarum Discord server. More people will be able to help there.
