### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by AuhNijGnahz** [clarkwinkelmann/catch-the-fish#2]
clarkwinkelmann-catch-the-fish:
    forum:
        moderate:
            add: 添加
            edit: 编辑
            delete: 删除
            fishes: 鱼的数量
            rounds: 总回合

        nav:
            rankings: 捕鱼排行榜
            settings: 捕鱼设置

        new-round-modal:
            title: 新回合

        new-fish-modal:
            title: 新的鱼

        edit-round-modal:
            title: 编辑回合 "{name}"

        edit-fish-modal:
            title: 编辑鱼 "{name}"

        caught-fish-modal:
            title: 哈，上钩 !
            named-by: 姓名
            placed-by: 放置者
            congratulation: 祝贺, 你抓到了一条鱼 ! 你一共抓到了 {catch_count} 条鱼.
            name: 鱼的名称
            name-help: 你可以将鱼的名称改成你喜欢的，但必须遵守社区规则
            placement-help: 你可以将鱼隐藏在近期的帖子或活跃用户的用户资料内，但是你不能抓你自己放置的鱼.
            submit-name-place-later: 保存名称并选个地方藏起来
            submit-name: 保存名称
            submit-place-later: 好的，我会选一个地方把它藏起来
            submit-continue: 继续
            submit-name-place-random: 保存名称并让鱼自己藏起来
            submit-place-random: 让鱼自己藏起来

        edit-round:
            name: 名称
            name-help: 这个回合的公开名称, 会显示在banner和排行榜中
            starts-at: 开始时间
            ends-at: 结束时间
            starting-pack: 新手礼包
            starting-pack-help: 这个礼包包含几条鱼，可以让你快速开始
            create: 创建回合
            save: 保存回合
            delete: 删除回合
            delete-confirmation: 确定删除回合 "{name}" 吗?

        edit-fish:
            name: 名称
            name-help: 鱼的当前名称。如果玩家有重命名鱼类的权限，他们可以编辑。
            create: 创建鱼类
            save: 保存鱼类
            delete: 删除鱼类
            delete-confirmation: 确定删除鱼类 "{name}" 吗?

        moving-fish:
            login: 登录后就可以开始抓鱼啦！

        fish-image:
            alt: 鱼类 "{name}" 的图片
            missing: 找不到这个鱼类的图片

        round-alert:
            message: 抓鱼行动 "{name}" 开始啦, 在结束时间 {time} 之前抓更多的鱼吧！
            rankings: 查看排名

        basket:
            title: 鱼筐
            drag-help: 将鱼拖放到讨论、帖子或用户个人中心上
            time: "放置到期时间: {time}"

        table-round:
            loading: 加载中...
            title: 回合
            new: 新回合
            name: 名称
            start: 从
            end: 直到
            actions: 操作
            edit: 编辑
            fishes: 鱼

        table-fish:
            loading: 加载中...
            title: 捕鱼行动 {name}
            new: 新的鱼
            image: 图片
            name: 名称
            user-name: 上一个命名者
            user-place: 最后放置者
            actions: 操作
            edit: 编辑
            no-user-name: 尚未被命名
            no-user-place: 随机
            upload: 上传新图片
            new-from-image: 通过批量图像导入创建新鱼

        table-ranking:
            loading: 加载中...
            title: 行动排名 {name}
            rank: 排名
            count: 抓到的鱼
            user: 用户

        page-ranking:
            title: 排行榜
            permission: 你无权查看排行榜
            nothing: 没有正在进行的行动

        drop-area:
            message: 你可以将鱼扔在这
            missing-from-store: 这条鱼似乎不存在

    admin:
        settings:
            title: 捕鱼设置
            discussion-age: 一个讨论存在多久才能被放鱼？（单位：天）
            post-age: 一个帖子存在多久才能被放鱼？（单位：天）
            user-age: 一个用户活跃多久才能被放鱼？（单位：天）
            time-to-place: 系统随机放置鱼前允许自己放置鱼的时间（单位：分钟）
            alert-round: 在主页上显示具有行动名称和持续时间的提示
            animate-flip: 根据方向翻转鱼图像

        permissions:
            visible: 可以看到鱼
            list-rankings: 访问捕鱼排行榜
            participate: 参加捕鱼
            choose-place: 自定放置鱼的位置
            choose-name: 给鱼命名
            moderate: 调整行动和鱼类

    api:
        default-fish-name: "#{number} 号鱼"
        wrong-catch-placement: 这里没有鱼。也许你不够快，让别人先拿到了
        too-many-placement-models: 一次只能放置一个位置
        invalid-discussion-id: 讨论似乎不存在，可能是最近删除的
        invalid-post-id: 帖子似乎不存在，可能是最近删除的。
        invalid-user-id: 用户似乎不存在，可能是最近删除的
        model-deleted: 无法将鱼放在已删除的讨论或帖子上
        model-private: 不能把鱼放在私人讨论或帖子上
        inactive-discussion: 不能将鱼置于非活动状态超过 {days} 天的讨论中
        inactive-post: 不能将鱼置于创建时间小于 {days} 天的帖子中
        inactive-user: 不能将鱼置于非活动状态超过 {days} 天的用户资料中
        non-comment-post: 只能在公开帖子上放置鱼
        user-suspended: 无法将鱼放在被封禁的用户身上
        random-error: 无法生成随机鱼位置
        cannot-catch-own-fish: 你不能抓自己放置的鱼
        cannot-catch-hold-fish: 前一个捕鱼人需要先把鱼放掉，然后你才能捕到它。
        fish-update-wrong-user: 您不能再编辑此鱼，它可能已被别人抓到
        fish-update-expired: 太晚了，你不能再编辑这条鱼了。同时它被自动放在某个地方
        round-not-started: 这一轮行动还没有开始
        round-finished: 这一轮行动已经结束了

**Comment by clarkwinkelmann** [comment]
Hello! Thanks for your contribution. However won't be adding translations for this extension.

I suggest you submit it to a language pack instead.
