### ISSUE TITLE
Leaderboards and fish baskets adapt to dark mode

### ISSUE THREAD

**Issue by riiamu39** [clarkwinkelmann/catch-the-fish#8]
At present, the leaderboard and fish basket are not displayed well in dark mode, which is obviously not suitable for dark mode.

To make them read well in dark mode, my forum is using this custom css. Hope that helps.

```
/* catchthefish color */
.catchthefish-table tr:nth-child(2n+1) td {
  background: none !important;
}
.catchthefish-basket {
  background: var(--body-bg) !important;
  color: var(--text-color) !important;
  border-radius: var(--border-radius);
  bottom: 1em !important;
  right: 1em !important;
  border: 1px solid #aaa !important;
}
```

Preview:

![image](https://user-images.githubusercontent.com/62450184/154629201-37561932-8de0-42cd-b61d-fbbf19b6db42.png)

![image](https://user-images.githubusercontent.com/62450184/154629097-57a4b6ee-ffca-4d6c-8fc3-0a67784d97dc.png)

![image](https://user-images.githubusercontent.com/62450184/154629139-3422a02d-679b-42f0-8940-768db4eab010.png)

**Comment by clarkwinkelmann** [comment]
I have changed the background and border colors in version 1.1.2. Thanks for the hints!
